name: Agregar miembros a la organización

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  agregar-miembros:
    runs-on: ubuntu-latest
    steps:
    - name: Agregar miembros a la organización
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GIT_TOKEN }}
        script: |
          const orgName = 'Trycatch-tv'
          const repoName = 'pipeline'

          const issues = await github.rest.issues.listForRepo({
            owner: orgName,
            repo: repoName,
            state: 'open'
          })

          for (const issue of issues.data) {
            const username = issue.title
            // Obtener la dirección de correo electrónico del usuario
            const userEmail = await github.rest.users.getByUsername({
              username: username
            })
            try {
              await github.rest.orgs.createInvitation({
                org: orgName,
                email: userEmail.data.email, // Usar la dirección de correo electrónico del usuario
                role: 'direct_member' // Usar 'direct_member' para agregar miembros directos
              })
              console.log(`Usuario ${username} agregado como miembro de la organización`)
            } catch (error) {
              console.log(`Error al agregar el usuario ${username}: ${error.message}`)
            }
          }
