name: Asignar Issues

on:
  workflow_dispatch:
    inputs:
      issue-number:
        description: 'Número de la issue a asignar'
        required: true

jobs:
  assign-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Asignar issue existente al usuario actual
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GIT_TOKEN }}
        script: |
          const orgName = 'Trycatch-tv'
          const destRepoName = 'trycatch_factory_site'
          const currentUser = context.actor
          const issueNumber = ${{ github.event.inputs.issue-number }}

          const opts = github.rest.issues.addAssignees.endpoint.merge({
            owner: orgName,
            repo: destRepoName,
            issue_number: issueNumber,
            assignees: [currentUser]
          })

          await github.rest.issues.addAssignees(opts)
