name: Agregar miembros a la organización

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  agregar-miembros:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener e invitar a nuevos miembros
        id: add-members
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          script: |
            const orgName = 'Trycatch-tv'
            const repoName = 'pipeline'

            const issues = await github.rest.issues.listForRepo({
              owner: orgName,
              repo: repoName,
              state: 'open'
            })

            for (const issue of issues.data) {
              const username = issue.title
              const user = await github.rest.users.getByUsername({ username: username })

              try {
                const members = await github.rest.orgs.listMembers({
                  org: orgName
                })
                const isMember = members.data.some(member => member.login === username)
                if (isMember) {
                  console.log(`El usuario ${username} ya es miembro de la organización`)
                  continue;
                }

                await github.rest.orgs.createInvitation({
                  org: orgName,
                  invitee_id: user.data.id,
                  role: 'direct_member'
                })
                console.log(`Usuario ${username} agregado como miembro de la organización`)

                const issueNumber = issue.number
                console.log(`Número de la issue: ${issueNumber}`)

              } catch (error) {
                console.log(`Error al agregar el usuario ${username}: ${error.message}`)
              }
            }
            console.log(`Última issue: ${issues.data.length > 0 ? issues.data[issues.data.length - 1].number : 'No issues found'}`)

      - name: Close Issue
        if: steps.add-members.outputs.issueNumber != null
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ steps.add-members.outputs.issueNumber }}
          comment: Auto-closing issue
