name: Agregar miembros a la organización

on:
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'

jobs:
  agregar-miembros:
    runs-on: ubuntu-latest
    steps:
    - name: Agregar miembros a la organización
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GIT_TOKEN }}
        script: |
          const orgName = 'Trycatch-tv'
          const repoName = 'pipeline'

          const issues = await github.rest.issues.listForRepo({
            owner: orgName,
            repo: repoName,
            state: 'open'
          })

          for (const issue of issues.data) {
            const username = issue.title
            const user = await github.rest.users.getByUsername({ username: username })

            try {
              await github.rest.orgs.createInvitation({
                org: orgName,
                invitee_id: user.data.id,
                role: 'direct_member'
              })
              console.log(`Usuario ${username} agregado como miembro de la organización`)

              await github.rest.issues.update({
                owner: orgName,
                repo: repoName,
                issue_number: issue.number,
                state: 'closed'
              })
              console.log(`Issue #${issue.number} cerrada`)
            } catch (error) {
              console.log(`Error al agregar el usuario ${username}: ${error.message}`)
            }
          }